### ISSUE TITLE
stop to work on 05th of january

### ISSUE THREAD

**Issue by echidne** [dennislwm/pydocker-cli#9]
hi!
The last list is from the 5th of january. The list is no more updated daily

**Comment by dennislwm** [comment]
Yup, I'll take a look at it. There is an issue with **GitHub Actions**, the update somehow broke my _actions.yml_ code.

**Comment by dennislwm** [comment]
Fixed. After investigating, the error wasn't because of GitHub Actions, but rather Python 3. The python-requests package (obsolete) is replaced with python3-requests.
